// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgpwCqnVQjEP2zEHRgBs_zAD40npmGBIk',
    appId: '1:848303744150:web:3a9d89c1d34b1dc7ee4eb7',
    messagingSenderId: '848303744150',
    projectId: 'chat-app-4121a',
    authDomain: 'chat-app-4121a.firebaseapp.com',
    storageBucket: 'chat-app-4121a.appspot.com',
    measurementId: 'G-T61LELBYNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGcPftxORjUnKKJsEZTQ2wPEb2Jvzm-I',
    appId: '1:848303744150:android:bbfc83ef6c9965b8ee4eb7',
    messagingSenderId: '848303744150',
    projectId: 'chat-app-4121a',
    storageBucket: 'chat-app-4121a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7vgD3jF9WChwRPoBNP3T3qhuQUiB7UI',
    appId: '1:848303744150:ios:5f7dd14cbf16bdb4ee4eb7',
    messagingSenderId: '848303744150',
    projectId: 'chat-app-4121a',
    storageBucket: 'chat-app-4121a.appspot.com',
    iosClientId: '848303744150-b8nghrn2i1cg12dujci771resclkaqlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
