// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi10OXSY_n9qgbAYXcKqUSS5Y4rlXhs10',
    appId: '1:777663264511:web:0694d1a1fa4c275ce7feca',
    messagingSenderId: '777663264511',
    projectId: 'fruits-commerce-app',
    authDomain: 'fruits-commerce-app.firebaseapp.com',
    storageBucket: 'fruits-commerce-app.appspot.com',
    measurementId: 'G-LQ16ZR28L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCapZJDFXx6ZYmoyZ73rYl7-KpcDaa7o',
    appId: '1:777663264511:android:2b80f78a4df8d444e7feca',
    messagingSenderId: '777663264511',
    projectId: 'fruits-commerce-app',
    storageBucket: 'fruits-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVhxQbp-m-BwS5NJw7brIpRd3KjdRkv4',
    appId: '1:777663264511:ios:c03041b28a0134eee7feca',
    messagingSenderId: '777663264511',
    projectId: 'fruits-commerce-app',
    storageBucket: 'fruits-commerce-app.appspot.com',
    iosClientId: '777663264511-afkhk9bp2mio8l3g78ig07qg4oncrov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerceApp',
  );
}
